# Generated by Django 4.2.11 on 2024-12-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_added_certificate_and_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'Tv Show')], max_length=255),
        ),
    ]
