# Generated by Django 4.2.11 on 2024-12-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_filmwork_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='type',
        ),
    ]
