# Generated by Django 4.2.11 on 2024-12-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_filmwork_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'Tv Show')], default='movie', max_length=255),
        ),
    ]
